# Import the required packages
from airflow import DAG
from airflow.operators.bash import BashOperator
from datetime import datetime, timedelta
from pathlib import Path
import tempfile

DAGS_DIR = Path(__file__).resolve().parent

WORK_DIR = (
    Path(tempfile.gettempdir())
    / "etl_toll_data"
    / "{{ run_id | replace(':', '_') | replace('+', '_') | replace('/', '_') }}"
)

# Define the default DAG arguments
default_args = {
    'owner': 'airflow',
    'start_date': datetime(2023, 1, 1), # Using a fixed date for idempotency
    # 'email': 'airflow@example.com',
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}

# Define the DAG with a descriptive ID
dag = DAG(
    'ETL_toll_data',
    default_args=default_args,
    description='A DAG for ETL processing of toll data',
    schedule="@daily",  # Run once every day
    catchup=False,
)


unzip_data = BashOperator(
    task_id='unzip_data',
    bash_command=f"""
      set -euo pipefail
      # Remove only artifacts generated by this DAG before starting a run.
      rm -rf -- "{WORK_DIR}"
      rm -f ./data/csv_data.csv ./data/tsv_data.csv \
            ./data/fixed_width_data.csv ./data/extracted_data.csv
      rm -rf -- ./staging

      mkdir -p -- "{WORK_DIR}"
      tar -xvzf "./data/tolldata.tgz" -C "{WORK_DIR}"
    """,
    dag=dag,
    cwd=str(DAGS_DIR)
)

extract_data_from_csv = BashOperator(
    task_id='extract_data_from_csv',
    bash_command='cut -d"," -f1,2,3,4 '
                 f'{WORK_DIR}/vehicle-data.csv '
                 '> ./data/csv_data.csv',
    dag=dag,
    cwd=str(DAGS_DIR)
)

extract_data_from_tsv = BashOperator(
    task_id="extract_data_from_tsv",
    cwd=str(DAGS_DIR),
    bash_command=f"""
      set -euo pipefail
      # extract cols 5–7, turn tabs into commas
      cut -f5,6,7 {WORK_DIR}/tollplaza-data.tsv | tr '\\t' ',' > ./data/tsv_data.csv
      # normalize CRLF -> LF
      sed -i 's/\\r$//' ./data/tsv_data.csv
      echo "Wrote ./data/tsv_data.csv (normalized to LF)"
    """,
    dag=dag,
)


extract_data_from_fixed_width = BashOperator(
    task_id="extract_data_from_fixed_width",
    cwd=str(DAGS_DIR),  # run relative to your DAGs folder
    bash_command=f"""
      set -euo pipefail
      awk '
        function trim(value) {{
          gsub(/^[[:space:]]+|[[:space:]]+$/, "", value)
          return value
        }}
        {{ print trim(substr($0, 1, 10)) "," trim(substr($0, 11, 10)) }}
      ' {WORK_DIR}/payment-data.txt > ./data/fixed_width_data.csv
      echo "Wrote ./data/fixed_width_data.csv"
    """,
    dag=dag,
)

consolidate_data = BashOperator(
    task_id='consolidate_data',
    bash_command='paste -d"," '
                 './data/csv_data.csv '
                 './data/tsv_data.csv '
                 './data/fixed_width_data.csv '
                 '> ./data/extracted_data.csv',
    dag=dag,
    cwd=str(DAGS_DIR)
)

transform_data = BashOperator(
    task_id="transform_data",
    cwd=str(DAGS_DIR),
    bash_command="""
      set -euo pipefail
      DATA_DIR=./data
      STAGING_DIR=./staging
      mkdir -p "$STAGING_DIR"

      # uppercase the 2nd field (vehicle_type)
      awk -F',' 'BEGIN{OFS=","} {$2=toupper($2); print}' "$DATA_DIR/extracted_data.csv" > "$STAGING_DIR/transformed_data.csv"

      echo "Wrote $STAGING_DIR/transformed_data.csv"
    """,
    dag=dag,
)

load_data = BashOperator(
    task_id="load_data",
    cwd=str(DAGS_DIR),
    bash_command="""
      set -euo pipefail
      SOURCE_FILE=./staging/transformed_data.csv
      FINAL_DIR=./staging/final
      FINAL_FILE="$FINAL_DIR/transformed_data.csv"

      test -s "$SOURCE_FILE"
      mkdir -p "$FINAL_DIR"
      cp "$SOURCE_FILE" "$FINAL_FILE"

      echo "Loaded $FINAL_FILE"
    """,
    dag=dag,
)


unzip_data >> [extract_data_from_csv, extract_data_from_tsv, extract_data_from_fixed_width] >> consolidate_data >> transform_data >> load_data
